### ISSUE TITLE
Timeout Error every few seconds/minutes

### ISSUE THREAD

**Issue by ghost** [thooton/muse#9]
I'm getting `TimeoutError()` from every API's every few seconds/minutes. I've to re-run the script to continue.

```
error in API1_REDACTED: TimeoutError()
error in API2_REDACTED: TimeoutError()
error in API3_REDACTED: TimeoutError()
error in API4_REDACTED: TimeoutError()
error in API5_REDACTED: TimeoutError()
error in API6_REDACTED: TimeoutError()
error in API7_REDACTED: TimeoutError()
error in API8_REDACTED: TimeoutError()
error in API9_REDACTED: TimeoutError()
error in API10_REDACTED: TimeoutError()
error in API11_REDACTED: TimeoutError()
error in API12_REDACTED: TimeoutError()
error in API13_REDACTED: TimeoutError()
```

I'm not quite sure whether it's a issue arising from my end or an issue within the script. It's a PITA to re-run the script every few seconds/minutes. I would like a permanent solution.

**Comment by thooton** [comment]
Hm, this is really strange, I'm not sure why it's happening unfortunately :(

On my side I have a VPN running with a script that changes the server every 3 minutes, perhaps that might work for you?

I'll do my best to reproduce and look into it.
